
# Lista de FIIs para auditar
tickers: [VILG11, BTLG11, HSLG11, GARE11, CPTS11, RVBI11, RZTR11,
          HSML11, XPLG11, VISC11, RZAK11, DEVA11]

# Telegram (obrigatório só se quiser alerta)
telegram_token: "COLE_SEU_TOKEN_AQUI"
telegram_chat_id: "COLE_SEU_CHATID"
