tickers: [VILG11, BTLG11, HSLG11, GARE11, CPTS11, RVBI11, RZTR11,
          HSML11, XPLG11, VISC11, RZAK11, DEVA11]

telegram_token: "7455490350:AAgr6NjFwrXFwkp-mq1HF2NBV-5PVXGfYY0"
telegram_chat_id: "6923018960"
